### ISSUE TITLE
[Feature]: 增加多工具查询功能，在调用工具前置一个query模型，以满足大量工具调用的场景需求

### ISSUE THREAD

**Issue by wzsage** [modelscope/agentscope#109]
**Is your feature request related to a problem? Please describe.**
可以参考这个项目
https://github.com/mMrBun/Chat2BI
思路如下
![Screenshot_2024-03-27-22-35-38-051_tv danmaku bili](https://github.com/modelscope/agentscope/assets/37926975/fd4222c2-552d-41e0-8689-cabbdd2a60f1)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavdGao** [comment]
Thanks for your suggestion! 

It seems like a combination of RAG and Tool usage, and will be helpful when there are too many tools. 
Currently we are building our RAG module in #64 , we will consider to add this feature after merging the RAG PR.
