### ISSUE TITLE
调用agent的speak方法，报错：Logger对象没有chat方法

### ISSUE THREAD

**Issue by tttonytan** [modelscope/agentscope#124]
**Describe the bug**
x = agent(x)

in speak
    logger.chat(content)
    ^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'chat'

是不是loguru版本不一样？

**Comment by pan-x-c** [comment]
`logger.chat` 方法是 AgentScope 引入的新方法，需要调用 `agentscope.init()` 之后才会注册到 logger 中，请确保在运行到该行之前已经调用过 `agentscope.init` 方法。AgentScope 的使用案例可以参考 `examples` 目录。

**Comment by tttonytan** [comment]
了解谢谢

**Comment by dengxiaotian123** [comment]
如果是自定义的 agent，如何使用 init 呢？

![Image](https://github.com/user-attachments/assets/c6a2f656-9397-4d0b-8986-ed56287951d6)

定义方式如上，使用下面的调用方式的时候出现，错误
```
    while True:
        x = jarvis(x)
        x= user_agent(x)
        if x.content == "exit":  # 用户输入"exit"退出对话
            break
```
```
    reply_result = original_reply(self, current_input)
  File "/Users/dh/miniconda3/envs/agentscp/lib/python3.9/site-packages/agentscope/agents/_user_agent.py", line 126, in reply
    self.speak(msg)
  File "/Users/dh/miniconda3/envs/agentscp/lib/python3.9/site-packages/agentscope/agents/_user_agent.py", line 164, in speak
    logger.chat(msg, disable_gradio=True)
AttributeError: 'Logger' object has no attribute 'chat'
```

**Comment by DavdGao** [comment]
@dengxiaotian123 在程序最开始调用agentscope.init()即可，不传入任何参数也可以，会在这个函数内向logger注册一个chat的monkey patch
