### ISSUE TITLE
[Bug]:ReActAgent call excute_python_code function with dashscope_chat model, Fail to parsing response.

### ISSUE THREAD

**Issue by Vincenttao** [modelscope/agentscope#130]
**Describe the bug**
When trying the official ReAct Agent example, using the dashscope_chat model with the qwen-max model and submitting a Python code model, it shows "fail parsing response".

**To Reproduce**

You code
YOUR_MODEL_CONFIGURATION = {
    "model_type": "dashscope_chat",
    "config_name": YOUR_MODEL_CONFIGURATION_NAME,
    "model_name": "qwen-max",
    "api_key": "XXX",
    # ...
}

How to execute
python conversation_with_react_agent.py
user input: Please help to execute Python code: print(1+2)
See error
WARNING  | agentscope.models.model:checking_wrapper:182 - Fail to parsing response: {
    "text": " ` ` ` json\n{\n    \"thought\": \"I am about to execute the provided Python code snippet.\",\n    \"speak\": \"The result of executing your Python code is coming up.\",\n    \"function\": [\n        {\n            \"name\": \"execute_python_code\",\n            \"arguments\": {\n                \"code\": \"print(1+2)\"\n            }\n        }\n    ]\n}\n ` ` ` ",
    "embedding": null,
    "image_urls": null,
    "raw": {
        "status_code": 200,
        "request_id": "c711e787-aa4a-96a3-967e-3818e838969e",
        "code": "",
        "message": "",
        "output": {
            "text": null,
            "finish_reason": null,
            "choices": [
                {
                    "finish_reason": "stop",
                    "message": {
                        "role": "assistant",
                        "content": "```json\n{\n    \"thought\": \"I am about to execute the provided Python code snippet.\",\n    \"speak\": \"The result of executing your Python code is coming up.\",\n    \"function\": [\n        {\n            \"name\": \"execute_python_code\",\n            \"arguments\": {\n                \"code\": \"print(1+2)\"\n            }\n        }\n    ]\n}\n```"
                    }
                }
            ]
        },
        "usage": {
            "input_tokens": 500,
            "output_tokens": 77,
            "total_tokens": 577
        }
    }
}.
 Exception: Expecting value: line 1 column 1 (char 0),   Attempt 1 / 3

![image](https://github.com/modelscope/agentscope/assets/24709015/2656444c-69c1-4272-95f4-3913bbf9f623)

**Environment (please complete the following information):**

- AgentScope Version: 0.0.2
- Python Version: 3.9
- OS: CentOS 7

**Additional context**
The model output **content.text** is:

"```" json\n{\n  \"thought\": \"I am executing the given Python code.\",\n  \"speak\": \"The result of the Python code execution is 3.\",\n  \"function\": [\n    {\n      \"name\": \"execute_python_code\",\n      \"arguments\": {\n        \"code\": \"print(1+2)\"\n      }\n    }\n  ]\n}\n "```"

 
 “```“ not "` ` `" 
![Uploading image.png…]()

the **parse_func()** function expects the part without the **```json\n** start and **\n```** end. Trying to modify **parse_func()** to add a conditional check for **response.text** can fix it.

**Comment by DavdGao** [comment]
It seems like qwen responds with a "```json" prefix and a suffix. Thanks for your report! We will try to adapt to qwen-max soon in #131 . 

As a hot fix, you can try to remove the prefix and suffix before executing `json.loads()`
