### ISSUE TITLE
能否支持在jupyter内部运行LLM生成的代码

### ISSUE THREAD

**Issue by JayLZhou** [modelscope/agentscope#133]
## 支持在jupyter环境运行LLM产生的代码
可以参考MetaGPT的实现
https://github.com/geekan/MetaGPT/blob/main/metagpt/actions/di/execute_nb_code.py#L30

## 优点如下:
1. 更好的定位错误，来让LLM来自我reflection修复代码
2. 对数据分析/数据科学任务更加友好
3. 可以输出数据分析的图例
4. 可以通过!pip xxx自动安装包来解决环境依赖问题
5. 更好的拆解复杂代码任务，如可以把代码分解到几个cell内部，分别执行每个cell，这样的成功率会更高

**Comment by DavdGao** [comment]
Update progress: Related to PR #231
