### ISSUE TITLE
请问支持中转的API吗？ 

### ISSUE THREAD

**Issue by zxy4567** [modelscope/agentscope#137]
在模型初始化过程中，比如这样的中转API：
openai.api_key = "sk-xxx"
openai.api_base = "https://api.xty.app/v1"
该怎么添加进
model_config = {
    "config_name": "{config_name}", # A unique name for the model config.
    "model_type": "openai",         # Choose from "openai", "openai_dall_e", or "openai_embedding".

    "model_name": "{model_name}",   # The model identifier used in the OpenAI API, such as "gpt-3.5-turbo", "gpt-4", or "text-embedding-ada-002".
    "api_key": "xxx",               # Your OpenAI API key. If unset, the environment variable OPENAI_API_KEY is used.
    "organization": "xxx",          # Your OpenAI organization ID. If unset, the environment variable OPENAI_ORGANIZATION is used.
}
中去呢？

**Comment by pan-x-c** [comment]
如果使用的是 openai 兼容接口（即可以支持 import openai 来调用），可以参考如下配置：
```
{
    "model_type": "openai",
    "config_name": "my_model_config",
    "api_key": "your key",
    "client_args": {
        "base_url": "http://xxx"
    },
    "generate_args": {
        "temperature": 0.5
    }
}
```
如果是完全自定义的中转 API，则需要在读懂 post_model.py 的情况下自行根据对应 API 要求的格式修改代码来兼容

**Comment by DavdGao** [comment]
If you have any questions， feel free to open new PR. Closing this pr for now.
