### ISSUE TITLE
在狼人杀example中，是怎么定义parse_func函数的

### ISSUE THREAD

**Issue by tomhup** [modelscope/agentscope#138]
如题。看到很多parse error报错，但是没有找到哪里定义的这个函数？

**Comment by DavdGao** [comment]
狼人杀用到的agent中定义的parse_func，实现在https://github.com/modelscope/agentscope/blob/main/src/agentscope/agents/dict_dialog_agent.py#L15

使用的地方在调用self.model的时候https://github.com/modelscope/agentscope/blob/main/src/agentscope/agents/dict_dialog_agent.py#L154

**Comment by tomhup** [comment]
提个建议，再parse报错时，日志提示是model模块下的wrapper，有点误导，不方便定位问题

**Comment by DavdGao** [comment]
> 提个建议，再parse报错时，日志提示是model模块下的wrapper，有点误导，不方便定位问题

好的，感谢建议，我们后续会继续改建报错信息这个模块
