### ISSUE TITLE
[Bug]:Gemini generates text error

### ISSUE THREAD

**Issue by NeilWang079** [modelscope/agentscope#149]
**Describe the bug**
When I am using gemini it keeps reporting 503 error, what should I do to fix it, my configuration and details of the error are as shown below

**To Reproduce**

![geminierror_1](https://github.com/modelscope/agentscope/assets/42379975/a658a9af-06ee-4083-90fb-ee0ecc907807)

**Expected behavior**

**Error messages**
![geminierror](https://github.com/modelscope/agentscope/assets/42379975/0ed7e731-ea64-466b-8d6d-9cc2d16a7beb)

**Environment (please complete the following information):**

- AgentScope Version: 0.0.2
- Python Version: 3.9
- OS:windows10

**Additional context**

**Comment by DavdGao** [comment]
@NeilWang079 Please first ensure you can use Gemini API in your location.

**Comment by NeilWang079** [comment]
> @NeilWang079 Please first ensure you can use Gemini API in your location.

I'm using vpn and I'm able to talk to the web version of Gemini.

One solution I see is to change genai.configure(api_key= f"{GOOGLE_API_KEY}") to genai.configure(api_key= f"{GOOGLE_API_KEY}", transport="rest"), this transport="rest"  how to configured in json.

**Comment by DavdGao** [comment]
Thanks for your reporting. We support additional parameters in `genai.configure` in #152
