### ISSUE TITLE
[Feature]: 期望增加本地化记忆存储功能，而且可以在重复运行程序的时候直接调用

### ISSUE THREAD

**Issue by wzsage** [modelscope/agentscope#150]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavdGao** [comment]
Thanks for your suggestion! We plan to implement this function by the following steps:

- [x] Support to serialize agent and memory. 
- [ ] Add an agent manager to allow serialize all agents at once. 
- [ ] Allow to load all agents and their memories in `agentscope.init(agent_configs="xxx")` function.

**Comment by DavdGao** [comment]
FYI: AgentScope supports memory loading and export. The related PR is #197
