### ISSUE TITLE
WorkStation中如何使用openai like api 是否可以自定义base_url

### ISSUE THREAD

**Issue by wzsage** [modelscope/agentscope#183]
![image](https://github.com/modelscope/agentscope/assets/37926975/b8454aa5-766d-4ffc-a246-622f34347eda)
model 模块中 的openaichat 是否可以自定义base_url，使用openailike api

**Comment by qbc2016** [comment]
你好，该功能已经添加，感谢反馈！

**Comment by ZiTao-Li** [comment]
Closing this issue as the new feature is added
