### ISSUE TITLE
Model Wrapper [PostAPIModelWrapperBase] is missing the required `format` method[Bug]:

### ISSUE THREAD

**Issue by messiGao** [modelscope/agentscope#187]
**Describe the bug**

**To Reproduce**

1. You code
2. How to execute
3. See error

**Expected behavior**

**Error messages**
Detailed error messages.

**Environment (please complete the following information):**

- AgentScope Version: [e.g. 0.0.2 via `print(agentscope.__version__)`]
- Python Version: [e.g. 3.9]
- OS: [e.g. macos, windows]

**Additional context**

**Comment by qbc2016** [comment]
Please run `pip install -e .` to update the version of AgentScope and set the `model_type` to `post_api_chat`.

**Comment by messiGao** [comment]
Okay, the previous POST API wasn't well-suited for Azure's API, but I've made the necessary adjustments myself.
