### ISSUE TITLE
[Bug]:Typo in Chinese README

### ISSUE THREAD

**Issue by Hitec-at** [modelscope/agentscope#198]
**Describe the bug**
![image](https://github.com/modelscope/agentscope/assets/33675009/a6ab5dfd-e7f6-4fcb-97d2-c6ba738d2a70)
![image](https://github.com/modelscope/agentscope/assets/33675009/605a98fc-daab-46f1-b2cf-b7e4dd4a1f02)

Happen to find out a tiny mistake.

**Comment by pan-x-c** [comment]
Thanks for reporting! We will fix it in #199
