### ISSUE TITLE
[Bug]: llama-index的版本号是多少

### ISSUE THREAD

**Issue by ForgetThatNight** [modelscope/agentscope#208]
在ragagent的example中import报错
from .llama_index_rag import LlamaIndexRAG
cannot import name 'BaseRetriever' from partially initialized module 'llama_index.core.base.base_retriever'

**Comment by FredericW** [comment]
你好，我们开发测目前的版本号是 0.10.26，不过这个看起来好像和版本关系不大，似乎是pip的时候有的module没装完整，建议试一下重新装一下llama-index试试

**Comment by ForgetThatNight** [comment]
> 你好，我们开发测目前的版本号是 0.10.26，不过这个看起来好像和版本关系不大，似乎是pip的时候有的module没装完整，建议试一下重新装一下llama-index试试

重装以后以解决
