### ISSUE TITLE
openai中转调用请教

### ISSUE THREAD

**Issue by nlper-hou** [modelscope/agentscope#214]
之前尝试的官网api都是没有问题的，现在买的中转api key使用受限，但是直接在官网上使用如下方式是可用的，
`from openai import OpenAI
client = OpenAI(api_key = "XXXX" ,base_url="XXXX")`
但是直接在
`model_configs=[
        {
            "model_type": "openai",
            "config_name": "gpt-3.5-turbo",
            "model_name": "gpt-3.5-turbo",
            "api_key": api_key, 
            "generate_args": {
                "temperature": temperature
            }
        }
    ]`
中修改出现openai.APIConnectionError: Connection error错误。
因此想请教是不是有什么方法可以支持openai的中转API调用？

**Comment by DavdGao** [comment]
转发OpenAI实际和FastChat以及vllm的使用方式一样，只需要指定base_url字段就可以，如下，官方的base_url字段被封装在client_args的base_url字段中
```
{
    "model_type": "openai_chat",
    "config_name": "gpt-3.5-turbo",
    "model_name": "gpt-3.5-turbo",
    "api_key": "xxx",
    "client_args": {
        "base_url": "xxx"
    },
    "generate_args": {
        "temperature": 1.0
    }
}
```

**Comment by nlper-hou** [comment]
> 转发OpenAI实际和FastChat以及vllm的使用方式一样，只需要指定base_url字段就可以，如下，官方的base_url字段被封装在client_args的base_url字段中
> 
> ```
> {
>     "model_type": "openai_chat",
>     "config_name": "gpt-3.5-turbo",
>     "model_name": "gpt-3.5-turbo",
>     "api_key": "xxx",
>     "client_args": {
>         "base_url": "xxx"
>     },
>     "generate_args": {
>         "temperature": 1.0
>     }
> }
> ```

多谢多谢，已试，成功。
