### ISSUE TITLE
agentscope invokes the ollama local model

### ISSUE THREAD

**Issue by ShuxianMa** [modelscope/agentscope#215]
What is the correct way to call ollama local model？
![截屏2024-05-13 16 45 12](https://github.com/modelscope/agentscope/assets/50402661/66ec57e5-52c2-46e7-97ea-6f86238bb517)

**Comment by pan-x-c** [comment]
You can use your ollama local model as described in the CPU Inference section of `examples/model_llama3/README.md`.
