### ISSUE TITLE
能不能支持调用本地的一些AI画图工具

### ISSUE THREAD

**Issue by NeilWang079** [modelscope/agentscope#220]
比如说agent调用comfyui进行图像的绘制

**Comment by DavdGao** [comment]
Thanks for your suggestion. Currently we are adding multimodal tools in #219 , and we will merge it as soon as possible.

**Comment by DavdGao** [comment]
The progress:
- [x] We have add example multimodal service functions in example-level #219 
- [x] 【WIP】We will integrate them into agentscope library, related to #255

**Comment by DavdGao** [comment]
Finish with #255
