### ISSUE TITLE
[Bug]:最新版本运行ollma api报错如下

### ISSUE THREAD

**Issue by wzsage** [modelscope/agentscope#229]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
运行reactagent直接报错
**To Reproduce**

agentscope.init(model_configs=[{
    "config_name": "my_ollama_chat_config",
    "model_type": "ollama_chat",
    "model_name": "qwen:32b",
    "options": {                                # Parameters passed to the model when calling
         "temperature": 0.5, "seed": 123,
    },
    "keep_alive": "5m",                         # Controls how long the model will stay loaded into memory
  }])

# Create agents
agent = ReActAgent(
    name="assistant",
    model_config_name="my_ollama_chat_config",
    verbose=True,
    service_toolkit=service_toolkit,
)
user = UserAgent(name="User")

# Build
x = None
while True:
    x = user(x)
    if x.content == "exit":
        break
    x = agent(x)

**Expected behavior**

**Error messages**
Detailed error messages.

Traceback (most recent call last):
  File "D:\pyproject\agentscope\examples\conversation_with_react_agent\code\conversation_with_react_agent.py", line 100, in <module>
    x = agent(x)
  File "D:\pyproject\agentscope\src\agentscope\agents\agent.py", line 294, in __call__
    res = self.reply(*args, **kwargs)
  File "D:\pyproject\agentscope\src\agentscope\agents\react_agent.py", line 164, in reply
    prompt = self.model.format(self.memory.get_memory(), hint_msg)
  File "D:\pyproject\agentscope\src\agentscope\models\ollama_model.py", line 269, in format
    "content": system_content_template.format(
KeyError: 'index'

**Environment (please complete the following information):**

- AgentScope Version: [0.0.4]
- Python Version: [3.10]
- OS: [e.g. macos, windows]

**Additional context**
![agentscope – conversation_with_react_agent py 2024_5_16 21_58_52](https://github.com/modelscope/agentscope/assets/37926975/6d92819c-d211-4023-a724-bacb6a105f8d)

**Comment by DavdGao** [comment]
Thanks for your reporting. That's very strange to have a key named "index" here. We will try to locate this bug.

**Comment by DavdGao** [comment]
The bug is fixed, please pull the repo to install the latest AgentScope library from source
