### ISSUE TITLE
the differences and relationships between Agentscope, Modelscope-Agent, and Qwen-Agent?

### ISSUE THREAD

**Issue by wuwujay** [modelscope/agentscope#244]
**<u>Could you explain the differences and relationships between Agentscope, Modelscope-Agent, and Qwen-Agent?
</u>**

**Comment by DavdGao** [comment]
AgentScope is a **developer-oriented** **multi-agent** platform, which focuses on the cooperation of multiple different agents, and features usability, robustness, distribution and transparency (to developers). Our target is to help developers to build multi-agent applications much more easily.

**Comment by DavdGao** [comment]
If you have any further questions or concerns, please feel free to create a new issue. Closing this for now.
