### ISSUE TITLE
[Bug]:已经定义了路径，但是对话的日志生成路径还是在默认文件夹

### ISSUE THREAD

**Issue by haike-1213** [modelscope/agentscope#259]
已经定义了路径，但是对话的日志生成路径还是在默认文件夹
![image](https://github.com/modelscope/agentscope/assets/63997166/22fa7571-49fa-491d-91e5-c6c137dbed12)
![image](https://github.com/modelscope/agentscope/assets/63997166/895d6d10-fd06-444f-933b-da49df47def0)

**Comment by haike-1213** [comment]
![image](https://github.com/modelscope/agentscope/assets/63997166/e156b494-9eec-4210-8ecf-66f4473fb8af)
为什么是分开的？

**Comment by pan-x-c** [comment]
感谢反馈，我们会尽快修复
