### ISSUE TITLE
[Bug]: logging error when use XML tags

### ISSUE THREAD

**Issue by czw90130** [modelscope/agentscope#264]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
使用LLM进行语句标注时，如果采用XML标签，则会引起日志报错。

**To Reproduce**

# -*- coding: utf-8 -*-
"""A simple example for conversation between user and assistant agent."""
import agentscope
from agentscope.agents import DialogAgent
from agentscope.agents.user_agent import UserAgent
from agentscope.pipelines.functional import sequentialpipeline
from agentscope.message import Msg
from prompt import Prompts
import json

def main() -> None:
    """A basic conversation demo"""

    survivors = agentscope.init(
        model_configs="./configs/model_configs.json",
        agent_configs="./configs/agent_configs.json",
    )
    
    with open("./configs/basic_tags.json", "r", encoding='utf-8') as f:
        json_data = json.load(f)
        tags_json_str = json.dumps(json_data['tags'])
        require_str = json_data['require']

    # Init use agents
    user_agent = UserAgent()

    # start the conversation between user and assistant
    x = None
    while x is None or x.content != "exit":
        x = user_agent()
        x = Prompts.annotate_task.format_map(
            {
                "tags": tags_json_str,
                "require": require_str,
                "info": x.content,
            }
        )
        x = Msg("annotator", x, role="user")
        x = survivors[0](x)
        print(x.content)

if __name__ == "__main__":
    main()

**Expected behavior**
对以下内容进行标注：
患者10月余前因“双肾结石8月余，左肾造瘘术后25天”就诊于*****医院，诊断“双肾结石”，具体治疗不详。2月余前因“反复畏寒发热、腰痛1个半月”入住我院，于2015-05-25行
左肾穿刺造瘘术+右输尿管dj管置入术，术中见：左肾重度积水，左肾萎缩，置管后引出脓性尿液。术后予以哌拉西林他唑巴坦4.5gq8hivgtt经验性抗感染及止血、补液等支持治疗。1 月余前再次入院，并于2015-06-17行左输尿管镜取石术，术后予抗感染及止血、补液等支持治疗。2周余前，患者因“右腰胀痛伴发热1周余”入住我院，并于2015-07-15行b超引导下右肾肾穿刺造瘘术，术中见右肾结石，穿刺后见浑浊尿液流出，导丝引导下放置8f造瘘管一根。术后予以亚胺培南西司他丁针0.5g静脉滴注q8h抗感染及止血补液等对症治疗。患者术后恢复可，2周内右腰部胀痛，无畏寒发热，无恶心呕吐等不适，今来我院继续治疗，拟“肾结石”收住入院。自病以来，神清，精神可，胃纳差，睡眠一般，小便由引流管引出，稍有便秘，体重10月内降低10斤。自诉发现糖尿病1年，注射胰岛素治疗半年后饮食治疗，血糖控制欠佳。

**Error messages**
Detailed error messages.

**Environment (please complete the following information):**
2024-05-28 13:43:05.489 | INFO     | agentscope.utils.monitor:register:417 - Register metric [gpt-4o.total_tokens] to SqliteMonitor with unit [token] and quota [None]
User input: 患者10月余前因“双肾结石8月余，左肾造瘘术后25天”就诊于*****医院，诊断“双肾结石”，具体治疗不详。2月余前因“反复畏寒发热、腰痛1个半月”入住我院，于2015-05-25行左肾穿刺造瘘术+右输尿管dj管置入术，术中见：左肾重度积水，左肾萎缩，置管后引出脓性尿液。术后予以哌拉西林他唑巴坦4.5gq8hivgtt经验性抗感染及止血、补液等支持治
疗。1月余前再次入院，并于2015-06-17行左输尿管镜取石术，术后予抗感染及止血、补液等支持治疗。2周余前，患者因“右腰胀痛伴发热1周余”入住我院，并于2015-07-15行b超引导
下右肾肾穿刺造瘘术，术中见右肾结石，穿刺后见浑浊尿液流出，导丝引导下放置8f造瘘管一根。术后予以亚胺培南西司他丁针0.5g静脉滴注q8h抗感染及止血补液等对症治疗。患者术后恢复可，2周内右腰部胀痛，无畏寒发热，无恶心呕吐等不适，今来我院继续治疗，拟“肾结石”收住入院。自病以来，神清，精神可，胃纳差，睡眠一般，小便由引流管引出，稍有便秘，体重10月内降低10斤。自诉发现糖尿病1年，注射胰岛素治疗半年后饮食治疗，血糖控制欠佳。
User: 患者10月余前因“双肾结石8月余，左肾造瘘术后25天”就诊于*****医院，诊断“双肾结石”，具体治疗不详。2月余前因“反复畏寒发热、腰痛1个半月”入住我院，于2015-05-25行
左肾穿刺造瘘术+右输尿管dj管置入术，术中见：左肾重度积水，左肾萎缩，置管后引出脓性尿液。术后予以哌拉西林他唑巴坦4.5gq8hivgtt经验性抗感染及止血、补液等支持治疗。1 月余前再次入院，并于2015-06-17行左输尿管镜取石术，术后予抗感染及止血、补液等支持治疗。2周余前，患者因“右腰胀痛伴发热1周余”入住我院，并于2015-07-15行b超引导下右肾肾穿刺造瘘术，术中见右肾结石，穿刺后见浑浊尿液流出，导丝引导下放置8f造瘘管一根。术后予以亚胺培南西司他丁针0.5g静脉滴注q8h抗感染及止血补液等对症治疗。患者术后恢复可，2周内右腰部胀痛，无畏寒发热，无恶心呕吐等不适，今来我院继续治疗，拟“肾结石”收住入院。自病以来，神清，精神可，胃纳差，睡眠一般，小便由引流管引出，稍有便秘，体重10月内降低10斤。自诉发现糖尿病1年，注射胰岛素治疗半年后饮食治疗，血糖控制欠佳。
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=35, microseconds=484413), 'exception': None, 'extra': {}, 'file': (name='logging_utils.py', path='C:\\Users\\pc\\Documents\\workspace\\agentscope\\src\\agentscope\\utils\\logging_utils.py'), 'function': '_chat', 'level': (name='CHAT_LOG', no=21, icon=' '), 'line': 117, 'message': '<green><b>Annotator</b></green>: 患者<tim>10月余前</tim>因<dis-dis>“双肾结石</dis-dis><tim>8月余</tim>，<dis-pos>左肾造瘘术后<tim>25天</tim></dis-pos>”就诊于<ins-hos>*****医院</ins-hos>，诊断<dis-dis>“双肾结石”</dis-dis>，具体治疗不详。<tim>2月余前</tim>因<sym-sym>“反复畏寒发热、腰痛<tim>1个半月</tim>”</sym-sym>入住<ins-myi>我院</ins-myi>，于<tim>2015-05-25</tim>行<thp-sur><bod-bdp>左肾穿刺造瘘术+右输尿管dj管置入术</bod-bdp></thp-sur>，术中见：<sym-sig>左肾重度积水， 左肾萎缩，置管后引出脓性尿液</sym-sig>。术后予以<thp-mdt>哌拉西林他唑巴坦4.5g q8h ivgtt经验性抗感染及止血、补液等支持治疗</thp-mdt>。<tim>1月余前</tim>再次入院，并于<tim>2015-06-17</tim>行<thp-sur>左输尿管镜取石术</thp-sur>，<dis-pos>术后</dis-pos>予<thp-mdt>抗感染及止血、补液等支持治疗</thp-mdt>。<tim>2周余前</tim>，患 者因<sym-sym>“右腰胀痛伴发热<tim>1周余</tim>”</sym-sym>入住<ins-myi>我院</ins-myi>，并于<tim>2015-07-15</tim>行<ite-img>b超引导下右肾肾穿刺造瘘术</ite-img>，术中见<sym-sig>右肾结石</sym-sig>，<sym-sig>穿刺后见浑浊尿液流出，导丝引导下放置8f造瘘管一根</sym-sig>。<dis-pos>术后</dis-pos>予<thp-mdt>亚胺培南西司他丁针0.5g静脉 滴注q8h抗感染及止血补液等对症治疗</thp-mdt>。患者<dis-pos>术后恢复可</dis-pos>，<tim>2周内</tim>右腰部<sym-sym>胀痛</sym-sym>，无<sym-sym>畏寒发热</sym-sym>，无<sym-sym>恶心呕吐</sym-sym>等不适，今来<ins-myi>我院</ins-myi>继续治疗，拟<dis-dis>“肾结石”</dis-dis>收住入院。自病以来，<sym-sym>神清，精神可</sym-sym>，<sym-sym>胃纳差，睡眠一般</sym-sym>，<sym-sym>小便由引流管引出，稍有便秘</sym-sym>，<sym-sig>体重<tim>10月内</tim>降低10斤</sym-sig>。自诉发现<dis-dis>糖尿病<tim>1年</tim></dis-dis>，<thp-mdt>注射胰岛素治疗<tim>半年后</tim>饮食治疗</thp-mdt>，<sym-sig>血糖控制欠佳</sym-sig>。', 'module': 'logging_utils', 'name': 'agentscope.utils.logging_utils', 'process': (id=13680, name='MainProcess'), 'thread': (id=21564, name='MainThread'), 'time': datetime(2024, 5, 28, 13, 43, 35, 656450, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_handler.py", line 135, in emit
    _, precomputed_format = self._memoize_dynamic_format(dynamic_format, ansi_level)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_handler.py", line 12, in prepare_colored_format
    colored = Colorizer.prepare_format(format_)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_colorizer.py", line 358, in prepare_format
    tokens, messages_color_tokens = Colorizer._parse_without_formatting(string)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_colorizer.py", line 450, in _parse_without_formatting
    parser.feed(literal_text, raw=recursive)
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_colorizer.py", line 253, in feed
    raise ValueError(
ValueError: Tag "<tim>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
--- End of logging error ---
--- Logging error in Loguru Handler #2 ---
Record was: {'elapsed': datetime.timedelta(seconds=35, microseconds=484413), 'exception': None, 'extra': {}, 'file': (name='logging_utils.py', path='C:\\Users\\pc\\Documents\\workspace\\agentscope\\src\\agentscope\\utils\\logging_utils.py'), 'function': '_chat', 'level': (name='CHAT_LOG', no=21, icon=' '), 'line': 117, 'message': '<green><b>Annotator</b></green>: 患者<tim>10月余前</tim>因<dis-dis>“双肾结石</dis-dis><tim>8月余</tim>，<dis-pos>左肾造瘘术后<tim>25天</tim></dis-pos>”就诊于<ins-hos>*****医院</ins-hos>，诊断<dis-dis>“双肾结石”</dis-dis>，具体治疗不详。<tim>2月余前</tim>因<sym-sym>“反复畏寒发热、腰痛<tim>1个半月</tim>”</sym-sym>入住<ins-myi>我院</ins-myi>，于<tim>2015-05-25</tim>行<thp-sur><bod-bdp>左肾穿刺造瘘术+右输尿管dj管置入术</bod-bdp></thp-sur>，术中见：<sym-sig>左肾重度积水， 左肾萎缩，置管后引出脓性尿液</sym-sig>。术后予以<thp-mdt>哌拉西林他唑巴坦4.5g q8h ivgtt经验性抗感染及止血、补液等支持治疗</thp-mdt>。<tim>1月余前</tim>再次入院，并于<tim>2015-06-17</tim>行<thp-sur>左输尿管镜取石术</thp-sur>，<dis-pos>术后</dis-pos>予<thp-mdt>抗感染及止血、补液等支持治疗</thp-mdt>。<tim>2周余前</tim>，患 者因<sym-sym>“右腰胀痛伴发热<tim>1周余</tim>”</sym-sym>入住<ins-myi>我院</ins-myi>，并于<tim>2015-07-15</tim>行<ite-img>b超引导下右肾肾穿刺造瘘术</ite-img>，术中见<sym-sig>右肾结石</sym-sig>，<sym-sig>穿刺后见浑浊尿液流出，导丝引导下放置8f造瘘管一根</sym-sig>。<dis-pos>术后</dis-pos>予<thp-mdt>亚胺培南西司他丁针0.5g静脉 滴注q8h抗感染及止血补液等对症治疗</thp-mdt>。患者<dis-pos>术后恢复可</dis-pos>，<tim>2周内</tim>右腰部<sym-sym>胀痛</sym-sym>，无<sym-sym>畏寒发热</sym-sym>，无<sym-sym>恶心呕吐</sym-sym>等不适，今来<ins-myi>我院</ins-myi>继续治疗，拟<dis-dis>“肾结石”</dis-dis>收住入院。自病以来，<sym-sym>神清，精神可</sym-sym>，<sym-sym>胃纳差，睡眠一般</sym-sym>，<sym-sym>小便由引流管引出，稍有便秘</sym-sym>，<sym-sig>体重<tim>10月内</tim>降低10斤</sym-sig>。自诉发现<dis-dis>糖尿病<tim>1年</tim></dis-dis>，<thp-mdt>注射胰岛素治疗<tim>半年后</tim>饮食治疗</thp-mdt>，<sym-sig>血糖控制欠佳</sym-sig>。', 'module': 'logging_utils', 'name': 'agentscope.utils.logging_utils', 'process': (id=13680, name='MainProcess'), 'thread': (id=21564, name='MainThread'), 'time': datetime(2024, 5, 28, 13, 43, 35, 656450, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_handler.py", line 131, in emit
    precomputed_format = self._memoize_dynamic_format(dynamic_format)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_handler.py", line 17, in prepare_stripped_format
    colored = Colorizer.prepare_format(format_)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_colorizer.py", line 358, in prepare_format
    parser.feed(literal_text, raw=recursive)
  File "C:\Users\pc\AppData\Roaming\Python\Python312\site-packages\loguru\_colorizer.py", line 253, in feed
    raise ValueError(
ValueError: Tag "<tim>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
--- End of logging error ---
患者<tim>10月余前</tim>因<dis-dis>“双肾结石</dis-dis><tim>8月余</tim>，<dis-pos>左肾造瘘术后<tim>25天</tim></dis-pos>”就诊于<ins-hos>*****医院</ins-hos>，诊断<dis-dis>“双肾结石”</dis-dis>，具体治疗不详。<tim>2月余前</tim>因<sym-sym>“ 反复畏寒发热、腰痛<tim>1个半月</tim>”</sym-sym>入住<ins-myi>我院</ins-myi>，于<tim>2015-05-25</tim>行<thp-sur><bod-bdp>左肾穿刺造瘘术+右输尿管dj管置入术</bod-bdp></thp-sur>，术中见：<sym-sig>左肾重度积水，左肾萎缩，置管后引出脓性尿液</sym-sig>。术后予以<thp-mdt>哌拉西林他唑巴坦4.5g q8h ivgtt经验性抗感染及止血、补液等支持治疗</thp-mdt>。<tim>1月余前</tim>再次入院，并于<tim>2015-06-17</tim>行<thp-sur>左输尿管镜取石术</thp-sur>，<dis-pos>术后</dis-pos>予<thp-mdt>抗感染及止血、补液等支持治疗</thp-mdt>。<tim>2周余前</tim>，患者因<sym-sym>“右腰胀痛伴发热<tim>1周余</tim>”</sym-sym>入住<ins-myi>我院</ins-myi>，并于<tim>2015-07-15</tim>行<ite-img>b超引导下右肾肾穿刺造瘘术</ite-img>，术中见<sym-sig>右肾结石</sym-sig>，<sym-sig>穿刺后见浑浊尿液流出，导丝引导下放置8f造瘘管一根</sym-sig>。<dis-pos>术后</dis-pos>予<thp-mdt>亚胺培南西司他丁针0.5g静脉滴注q8h抗感染及止血补液等对症治疗</thp-mdt>。患者<dis-pos>术后恢复可</dis-pos>，<tim>2周 内</tim>右腰部<sym-sym>胀痛</sym-sym>，无<sym-sym>畏寒发热</sym-sym>，无<sym-sym>恶心呕吐</sym-sym>等不适，今来<ins-myi>我院</ins-myi>继续治疗，拟<dis-dis>“肾结石”</dis-dis>收住入院。自病以来，<sym-sym>神清，精神可</sym-sym>，<sym-sym>胃纳差，睡眠一般</sym-sym>，<sym-sym>小便由引流管引出，稍有便秘</sym-sym>，<sym-sig>体重<tim>10月内</tim>降低10斤</sym-sig>。自诉发现<dis-dis>糖尿病<tim>1年</tim></dis-dis>，<thp-mdt>注射胰岛素治疗<tim>半年后</tim>饮食治疗</thp-mdt> ，<sym-sig>血糖控制欠佳</sym-sig>。

- AgentScope Version: 0.0.4
- Python Version: 3.12
- OS: windows 11

**Comment by pan-x-c** [comment]
This issue appears to be the same as  #259  and #227  . We are currently working on a resolution.
