### ISSUE TITLE
[Bug]: Error occurs when sending a message larger than 4MB in distributed mode 

### ISSUE THREAD

**Issue by pan-x-c** [modelscope/agentscope#269]
**Describe the bug**
As the title says. 

Since the default maximum message length of gRPC is 4MB, the distributed mode of AgentScope cannot send messages larger than this value. However, simply increasing this value will occupy more resources and reduce performance.

**Comment by DavdGao** [comment]
If the message is indeed larger than 4MB, the communication workload is avoidless, right?

**Comment by pan-x-c** [comment]
A possible solution is checking the message size before sending/receiving, and automatically switching to the stream mode of gRPC if the message is too large.
