### ISSUE TITLE
ModuleNotFoundError: No module named 'agentscope.service.multi_modality'

### ISSUE THREAD

**Issue by UCC-team** [modelscope/agentscope#286]
ModuleNotFoundError: No module named 'agentscope.service.multi_modality'
<img width="962" alt="image" src="https://github.com/modelscope/agentscope/assets/35629974/a9481e58-01df-458f-8503-dcdc51a95ea4">

**Comment by pan-x-c** [comment]
This bug is fixed in version 0.0.5a1, you can install it with `pip install agentscope==0.0.5a1`. We will release a new version soon to resolve the issue.
