### ISSUE TITLE
[Feature]: 有没有has_init方法查看是否已经初始化？避免重复初始化

### ISSUE THREAD

**Issue by haike-1213** [modelscope/agentscope#303]
agentscope.init

**Comment by pan-x-c** [comment]
感谢提醒。目前还没有类似 `has_init` 的方法，我们会在后续的版本中在 `init` 函数中增加判断逻辑来避免重复初始化

**Comment by DavdGao** [comment]
FYI: We have provided a function named `agentscope.state_dict` in #364  for the state of agentscope

**Comment by DavdGao** [comment]
Feel free to create a new issue if needed, closing this for now.
