### ISSUE TITLE
How to use the local embedding model for text vectorization？

### ISSUE THREAD

**Issue by hingkan** [modelscope/agentscope#315]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**
This is a problem I recently encountered using the AgentScope RAG module.
URL: https://modelscope.github.io/agentscope/en/tutorial/210-rag.html

API interfaces are used on both the model and embedding of the AgentScope RAG. And the agentscope\scripts\flask_transformers\setup_hf_service.py script starts the model is also LLM.
There is no corresponding embedding API deployment mode.

How to use the local embedding model for text vectorization.

**Comment by DavdGao** [comment]
@FredericW @ZiTao-Li Please check this issue.

**Comment by ZiTao-Li** [comment]
> @FredericW @ZiTao-Li Please check this issue.

Sure, we will provide an example as soon as possible.

**Comment by hingkan** [comment]
> > @FredericW @ZiTao-Li Please check this issue.
> 
> Sure, we will provide an example as soon as possible.
Thank you. Looking forward to it.
