### ISSUE TITLE
在AgentScope Studio中，如何让finished状态的Agent重新启动？

### ISSUE THREAD

**Issue by hzb3666998** [modelscope/agentscope#319]
在AgentScope Studio中，如何让finished状态的Agent重新启动？
<img width="1228" alt="1122" src="https://github.com/modelscope/agentscope/assets/62230113/703edc95-aa70-4580-b3c7-99364a6525a6">

**Comment by pan-x-c** [comment]
目前版本暂时不支持重启 Finished 状态的 Agent，不过我们目前正在开发 Agent 检查点相关功能，会允许 Agent 加载过去的检查点从而恢复运行状态，该功能会在后续发布

**Comment by hzb3666998** [comment]
明白了，谢谢。
