### ISSUE TITLE
[Bug]:杀掉 AgentScope Studio后，再次启动，Agent处于waiting状态，但不可以进行对话。

### ISSUE THREAD

**Issue by hzb3666998** [modelscope/agentscope#320]
开始状态Agent可以进行对话，如图：
<img width="1238" alt="1122" src="https://github.com/modelscope/agentscope/assets/62230113/9746d261-b136-4602-b91e-d3e206b3c8d3">
杀掉AgentScope Studio进程

**Comment by hzb3666998** [comment]
<img width="351" alt="1" src="https://github.com/modelscope/agentscope/assets/62230113/08eacd59-dbd5-4b88-b03f-c29801a27942">
再次启动，Agent处于waiting状态，但不可以进行对话。
<img width="1228" alt="112233" src="https://github.com/modelscope/agentscope/assets/62230113/08298994-33e6-4126-837e-76b9628f09e2">

**Comment by hzb3666998** [comment]
![image](https://github.com/modelscope/agentscope/assets/62230113/1804e03b-709c-48b9-88de-523b87a25ccc)

**Comment by DavdGao** [comment]
Currently, the communication between the AgentScope studio and python application is implemented by web socket. Once the studio is shut down, the web socket is closed. So for now the AgentScope Studio shouldn't be closed when the registered application is still running. 

Besides, we have planned to implemented the reconnected functionality in #310 , and we will fix it as soon as possible.

**Comment by hzb3666998** [comment]
ok，thanks
