### ISSUE TITLE
[Bug]: 502 Bad Gateway

### ISSUE THREAD

**Issue by AnthonyT42** [modelscope/agentscope#321]
<html>
<body>

URL: | https://agentscope.aliyun.com:2443/
<br>
Server: | tongyijieru-aliyun-com-hk71-011193012051.hk71
<br>
Date: | 2024/06/29 00:38:06

</body>
</html>

**Comment by rayrayraykk** [comment]
The workstation website has been moved to https://agentscope.io/ 
Thank you!

**Comment by DavdGao** [comment]
Feel free to open a new issue, closing this for now.
