### ISSUE TITLE
[Bug]:[RAG]一直提示我找不到信息，请帮忙看下我错在哪里

### ISSUE THREAD

**Issue by NeilWang079** [modelscope/agentscope#340]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
Please provide me with the text from which you'd like me to extract information about the three brothers in Juul County. I need the context to answer your question!
![屏幕截图 2024-07-15 182516](https://github.com/user-attachments/assets/c35730b4-507d-45da-991b-0abc674d2008)
![屏幕截图 2024-07-15 182735](https://github.com/user-attachments/assets/07424e50-9977-400d-bbb9-f1cb3f200ed3)

**Comment by ZiTao-Li** [comment]
It seems you replace data sources of the rag example and the program does not report any run time error.
Can you provide the information 1) the text chunks retrieved for this question from your prepared data 2) which model you are using?

**Comment by NeilWang079** [comment]
> It seems you replace data sources of the rag example and the program does not report any run time error. Can you provide the information 1) the text chunks retrieved for this question from your prepared data 2) which model you are using?

embedding:gte-qwen2-7b-instruct-embed-f16
llm:gemma2:27b
file type ：pdf
![屏幕截图 2024-07-16 015254](https://github.com/user-attachments/assets/df5ea514-ead1-413b-9469-405989b23816)

**Comment by ZiTao-Li** [comment]
> > It seems you replace data sources of the rag example and the program does not report any run time error. Can you provide the information 1) the text chunks retrieved for this question from your prepared data 2) which model you are using?
> 
> embedding:gte-qwen2-7b-instruct-embed-f16 llm:gemma2:27b file type ：pdf ![屏幕截图 2024-07-16 015254](https://private-user-images.githubusercontent.com/42379975/348806689-df5ea514-ead1-413b-9469-405989b23816.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjYzMTgsIm5iZiI6MTcyMTA2NjAxOCwicGF0aCI6Ii80MjM3OTk3NS8zNDg4MDY2ODktZGY1ZWE1MTQtZWFkMS00MTNiLTk0NjktNDA1OTg5YjIzODE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE3NTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNGQ1M2MwNTQ1YzY0NTRkOWVlZmY0ZDAzYzQwN2I2NTNkYWQyM2M1YzZiNWUyZDhkNGI0MDI1N2MxMjMwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U6hHOx0DcTpSvXUdqMr1JsT9RI6B1hHr0lxerskTppA)

My conjecture is that llamaindex's default `SimpleDirectoryReader` fails to parse this pdf file. You can turn `"log_retrieval"` to `true` in the agent config to print the retrieved chunks for of this question. If those are not human readable, then that's probably the issue.

**Comment by NeilWang079** [comment]
> > > It seems you replace data sources of the rag example and the program does not report any run time error. Can you provide the information 1) the text chunks retrieved for this question from your prepared data 2) which model you are using?
> > 
> > 
> > embedding:gte-qwen2-7b-instruct-embed-f16 llm:gemma2:27b file type ：pdf ![屏幕截图 2024-07-16 015254](https://private-user-images.githubusercontent.com/42379975/348806689-df5ea514-ead1-413b-9469-405989b23816.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjYzMTgsIm5iZiI6MTcyMTA2NjAxOCwicGF0aCI6Ii80MjM3OTk3NS8zNDg4MDY2ODktZGY1ZWE1MTQtZWFkMS00MTNiLTk0NjktNDA1OTg5YjIzODE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE3NTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNGQ1M2MwNTQ1YzY0NTRkOWVlZmY0ZDAzYzQwN2I2NTNkYWQyM2M1YzZiNWUyZDhkNGI0MDI1N2MxMjMwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U6hHOx0DcTpSvXUdqMr1JsT9RI6B1hHr0lxerskTppA)
> 
> My conjecture is that llamaindex's default `SimpleDirectoryReader` fails to parse this pdf file. You can turn `"log_retrieval"` to `true` in the agent config to print the retrieved chunks for of this question. If those are not human readable, then that's probably the issue.

>>>> content:
>>>> score:0.18777823325891718
>>>> source:page_label: 329
file_name: 3.pdf
file_path: O:\agentscope\docs\fiction\3.pdf
file_type: application/pdf
file_size: 18620341
creation_date: 2024-07-15
last_modified_date: 2024-07-15
>>>> content:
>>>> score:0.18734724511061887
>>>> source:page_label: 321
file_name: 3.pdf
file_path: O:\agentscope\docs\fiction\3.pdf
file_type: application/pdf
file_size: 18620341
creation_date: 2024-07-15
last_modified_date: 2024-07-15
>>>> content:
>>>> score:0.18725543754810822
>>>> source:page_label: 328
file_name: 3.pdf
file_path: O:\agentscope\docs\fiction\3.pdf
file_type: application/pdf
file_size: 18620341
creation_date: 2024-07-15
last_modified_date: 2024-07-15
>>>> content:
>>>> score:0.18567446110272431
>>>> source:page_label: 326
file_name: 3.pdf
file_path: O:\agentscope\docs\fiction\3.pdf
file_type: application/pdf
file_size: 18620341
creation_date: 2024-07-15
last_modified_date: 2024-07-15
>>>> content:
2024-07-16 10:53:00.559 | INFO     | agentscope.agents.rag_agent:reply:161 - {
    "text": "NO \n\nThe provided content appears to be metadata and excerpts from a PDF file, but doesn't contain information about the names of the three brothers from Julu County.  \n",
    "embedding": null,
    "image_urls": null,
    "parsed": null,
    "raw": {
        "model": "gemma2:27b",
        "created_at": "2024-07-16T02:53:00.545041Z",
        "message": {
            "role": "assistant",
            "content": "NO \n\nThe provided content appears to be metadata and excerpts from a PDF file, but doesn't contain information about the names of the three brothers from Julu County.  \n"
        },
        "done_reason": "stop",
        "done": true,
        "total_duration": 12650800300,
        "load_duration": 10303735000,
        "prompt_eval_count": 662,
        "prompt_eval_duration": 912066000,
        "eval_count": 38,
        "eval_duration": 1433258000
    }
}
2024-07-16 10:53:02.303 | WARNING  | agentscope.message:__init__:150 - A new field `role` is newly added to the message. Please specify the role of the message. Currently we use a default "assistant" value.
Book-Assistant: The names of the three brothers from Julu County are **not mentioned** in the provided context. Please provide me with the text where you encountered these characters so I can assist you further.  
The contents of the logging.log file is this

**Comment by ZiTao-Li** [comment]
> > > > It seems you replace data sources of the rag example and the program does not report any run time error. Can you provide the information 1) the text chunks retrieved for this question from your prepared data 2) which model you are using?
> > > 
> > > 
> > > embedding:gte-qwen2-7b-instruct-embed-f16 llm:gemma2:27b file type ：pdf ![屏幕截图 2024-07-16 015254](https://private-user-images.githubusercontent.com/42379975/348806689-df5ea514-ead1-413b-9469-405989b23816.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjYzMTgsIm5iZiI6MTcyMTA2NjAxOCwicGF0aCI6Ii80MjM3OTk3NS8zNDg4MDY2ODktZGY1ZWE1MTQtZWFkMS00MTNiLTk0NjktNDA1OTg5YjIzODE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE3NTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNGQ1M2MwNTQ1YzY0NTRkOWVlZmY0ZDAzYzQwN2I2NTNkYWQyM2M1YzZiNWUyZDhkNGI0MDI1N2MxMjMwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U6hHOx0DcTpSvXUdqMr1JsT9RI6B1hHr0lxerskTppA)
> > 
> > 
> > My conjecture is that llamaindex's default `SimpleDirectoryReader` fails to parse this pdf file. You can turn `"log_retrieval"` to `true` in the agent config to print the retrieved chunks for of this question. If those are not human readable, then that's probably the issue.
> 
> > > > > content:
> > > > > score:0.18777823325891718
> > > > > source:page_label: 329
> > > > > file_name: 3.pdf
> > > > > file_path: O:\agentscope\docs\fiction\3.pdf
> > > > > file_type: application/pdf
> > > > > file_size: 18620341
> > > > > creation_date: 2024-07-15
> > > > > last_modified_date: 2024-07-15
> > > > > content:
> > > > > score:0.18734724511061887
> > > > > source:page_label: 321
> > > > > file_name: 3.pdf
> > > > > file_path: O:\agentscope\docs\fiction\3.pdf
> > > > > file_type: application/pdf
> > > > > file_size: 18620341
> > > > > creation_date: 2024-07-15
> > > > > last_modified_date: 2024-07-15
> > > > > content:
> > > > > score:0.18725543754810822
> > > > > source:page_label: 328
> > > > > file_name: 3.pdf
> > > > > file_path: O:\agentscope\docs\fiction\3.pdf
> > > > > file_type: application/pdf
> > > > > file_size: 18620341
> > > > > creation_date: 2024-07-15
> > > > > last_modified_date: 2024-07-15
> > > > > content:
> > > > > score:0.18567446110272431
> > > > > source:page_label: 326
> > > > > file_name: 3.pdf
> > > > > file_path: O:\agentscope\docs\fiction\3.pdf
> > > > > file_type: application/pdf
> > > > > file_size: 18620341
> > > > > creation_date: 2024-07-15
> > > > > last_modified_date: 2024-07-15
> > > > > content:
> > > > > 2024-07-16 10:53:00.559 | INFO     | agentscope.agents.rag_agent:reply:161 - {
> > > > > "text": "NO \n\nThe provided content appears to be metadata and excerpts from a PDF file, but doesn't contain information about the names of the three brothers from Julu County.  \n",
> > > > > "embedding": null,
> > > > > "image_urls": null,
> > > > > "parsed": null,
> > > > > "raw": {
> > > > > "model": "gemma2:27b",
> > > > > "created_at": "2024-07-16T02:53:00.545041Z",
> > > > > "message": {
> > > > > "role": "assistant",
> > > > > "content": "NO \n\nThe provided content appears to be metadata and excerpts from a PDF file, but doesn't contain information about the names of the three brothers from Julu County.  \n"
> > > > > },
> > > > > "done_reason": "stop",
> > > > > "done": true,
> > > > > "total_duration": 12650800300,
> > > > > "load_duration": 10303735000,
> > > > > "prompt_eval_count": 662,
> > > > > "prompt_eval_duration": 912066000,
> > > > > "eval_count": 38,
> > > > > "eval_duration": 1433258000
> > > > > }
> > > > > }
> > > > > 2024-07-16 10:53:02.303 | WARNING  | agentscope.message:**init**:150 - A new field `role` is newly added to the message. Please specify the role of the message. Currently we use a default "assistant" value.
> > > > > Book-Assistant: The names of the three brothers from Julu County are **not mentioned** in the provided context. Please provide me with the text where you encountered these characters so I can assist you further.
> > > > > The contents of the logging.log file is this

It seems this is because your PDF file can't be parsed by the default Llamaindex pdf parser, so there is no useful information. You can either first convert the PDF into plain text format, or try with some other files.

I will close this issue for now as it is not a issue with AgentScope. But please let us know if you have any comments.
