### ISSUE TITLE
[Feature]: load agentscope studio model from python

### ISSUE THREAD

**Issue by wujiren** [modelscope/agentscope#349]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Is your feature request related to a problem? Please describe.**
agentscope studio is awesome, if it could be load from python, it will be great.

**Describe the solution you'd like**
load agentscope studio html from python

**Describe alternatives you've considered**
or transfer python codes to agentscope html

**Comment by DavdGao** [comment]
Thanks for your attention. 

I want to confirm if the "agentscope studio html" refers to the config exported from workstation(the dragging-and-dropping interface)?

**Comment by wujiren** [comment]
> Thanks for your attention.
> 
> I want to confirm if the "agentscope studio html" refers to the config exported from workstation(the dragging-and-dropping interface)?

yes, i hope i can load python code in the inrerface
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/88b35aa3-5bdb-49eb-92f0-91db3396c899">

**Comment by DavdGao** [comment]
Thank you for your suggestions. 

However, extracting a workflow from Python code is essentially equivalent to building a compiler system, which is challenging for our limited developement team.

For now, we are planning to support save and load workflow in our workstation for continuous development, hoping these features could help.

**Comment by DavdGao** [comment]
Thanks for your attention again. 

If you have any other questions, please feel free to create a new issue, closing this for now.
