### ISSUE TITLE
agentscope  Error loading ollama model

### ISSUE THREAD

**Issue by Jackmoyu001** [modelscope/agentscope#363]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

I have encountered some issues while using agentscope and I hope to receive your help.

Here are some of my parameters and code

model_config_test.json
```
[
    {
        "config_name": "ollama_qwen2_config",
        "model_type": "ollama_chat",
        "model_name": "qwen2",              
        "options": {                                
            "temperature": 0
        }
    }
]

```

My code

```
import agentscope
from agentscope.agents import DialogAgent
from agentscope.agents.user_agent import UserAgent
import os,json

with open('./configs/model_config_test.json','r',encoding='utf-8') as fr:
    model_config = json.load(fr)

agentscope.init(
    model_configs= model_config
)

dialog_agent = DialogAgent(
    name="Assistant",
    sys_prompt="你是个乐于助人的助手。",
    model_config_name="ollama_qwen2_config",  # 其中一个你在上面步骤准备好的配置名字（config_name对应的值）
)

user_agent = UserAgent()
x = None
while x is None or x.content != "exit":
    x = dialog_agent(x)
    x = user_agent(x)

```

Program error message

httpx.ConnectError: [Errno 111] Connection refused

###
Also, where should I add my ollama URL or how should I modify my program to make it run

**Comment by DavdGao** [comment]
- If your code is running on the same machine with ollama, you don't need to set ollama URL. 
- I have tried to reproduce the error with the following code, but it works normally
```python
import agentscope
from agentscope.agents import DialogAgent
from agentscope.agents.user_agent import UserAgent
import os,json

# with open('./configs/model_config_test.json','r',encoding='utf-8') as fr:
#     model_config = json.load(fr)

agentscope.init(
    model_configs= {
    "model_type": "ollama_chat",
    "config_name": "ollama_qwen2_config",

    "model_name": "qwen2",
}
)

dialog_agent = DialogAgent(
    name="Assistant",
    sys_prompt="你是个乐于助人的助手。",
    model_config_name="ollama_qwen2_config",  # 其中一个你在上面步骤准备好的配置名字（config_name对应的值）
)

user_agent = UserAgent()
x = None
while x is None or x.content != "exit":
    x = dialog_agent(x)
    x = user_agent(x)
```
![image](https://github.com/user-attachments/assets/3fa92885-7e88-4c1c-b9ba-f63df63eb6c0)

**Comment by DavdGao** [comment]
Fow now, the built-in ollama model wrapper in AgentScope only supports local ollama server.

**Comment by DavdGao** [comment]
@Jackmoyu001 
We have added a new argument "host" in ollama model configuration in #365 , you can use it as follows:
```json
{
    "model_type": "ollama_chat",
    "config_name": "xxx",
    "model_name": "qwen2",
    "host": "{YOUR_HOST}:{YOUR_PORT}"
}
```

**Comment by Jackmoyu001** [comment]
> 我们在 #365 的 ollama 模型配置中添加了一个新参数 “host”，您可以按如下方式使用：
> 
> ```json
> {
>     "model_type": "ollama_chat",
>     "config_name": "xxx",
>     "model_name": "qwen2",
>     "host": "{YOUR_HOST}:{YOUR_PORT}"
> }
> ```

Thank you very much
