### ISSUE TITLE
the qr code of  wechat has expired

### ISSUE THREAD

**Issue by ChristopheZhao** [modelscope/agentscope#37]
Hi, thank  you for your nice work about such an agent platform, the qr code of  wechat group has expired, can you update a new one?

**Comment by DavdGao** [comment]
Thanks for your attention!

**Comment by DavdGao** [comment]
Thanks for your attention! 

We have checked the QR code of wechat, and it's valid. Please retry the QR code in README.md or the following one within 7 days.

![IMG_4428](https://github.com/modelscope/agentscope/assets/102287034/c2d820b0-bd05-42ab-8cb3-63fadd43d73c)

**Comment by ChristopheZhao** [comment]
It works now,thanks.
