### ISSUE TITLE
[Bug]:api key and multimodal support for litellm_model

### ISSUE THREAD

**Issue by zyzhang1130** [modelscope/agentscope#372]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
1. From my testing, for `litellm_chat`, specifying `"api_key"` in `model_configs` does not work. `os.environ["ANTHROPIC_API_KEY"]` works but this is not ideal.

2. It seems `LiteLLMChatWrapper` currently does not support image modality while many models available on `litellm` do support it. Hope this can be addressed.

**To Reproduce**
using any agent with `litellm_chat`.

**Expected behavior**
Any agent-based examples should get responses from the respective model api.

**Error messages**
using Anthropic model with the following model config:
```
{
    "config_name": "lite_llm_claude3",
    "model_type": "litellm_chat",
    "model_name": "claude-3-opus-20240229",
    "api_key": xxx,
    "generate_args": {
                    "temperature": 0.2,
                },
}
```
will get the error message:
```
Exception has occurred: APIConnectionError
Missing Anthropic API Key - A call is being made to anthropic but no key is set either in the environment variables or via params
ValueError: Missing Anthropic API Key - A call is being made to anthropic but no key is set either in the environment variables or via params

During handling of the above exception, another exception occurred:

  File "/Users/zhangzeyu/Documents/agentscope/src/agentscope/models/litellm_model.py", line 159, in __call__
    response = litellm.completion(
  File "/Users/zhangzeyu/Documents/agentscope/src/agentscope/models/model.py", line 122, in checking_wrapper
    response = model_call(self, *args, **kwargs)
  File "/Users/zhangzeyu/Documents/agentscope/src/agentscope/agents/react_agent.py", line 168, in reply
    res = self.model(
  File "/Users/zhangzeyu/Documents/agentscope/src/agentscope/agents/agent.py", line 296, in __call__
    res = self.reply(*args, **kwargs)
  File "/Users/zhangzeyu/Documents/agentscope/examples/neurosymbolic_QA/neurosymbolic_QA.py", line 196, in <module>
    x = student_agent1(x)
litellm.exceptions.APIConnectionError: Missing Anthropic API Key - A call is being made to anthropic but no key is set either in the environment variables or via params
```

**Environment (please complete the following information):**

- AgentScope Version: 0.0.6alpha3
- Python Version: 3.10.14
- OS: macos

**Comment by garyzhang99** [comment]
https://github.com/modelscope/agentscope/blob/main/src/agentscope/models/litellm_model.py#L73

For litellm, the API key is retrieved from the environment, as detailed in the documentation available at https://docs.litellm.ai/docs/. I am uncertain about how you can support API keys for various models in a unified manner.

**Comment by zyzhang1130** [comment]
> https://github.com/modelscope/agentscope/blob/main/src/agentscope/models/litellm_model.py#L73
> 
> For litellm, the API key is retrieved from the environment, as detailed in the documentation available at https://docs.litellm.ai/docs/. I am uncertain about how you can support API keys for various models in a unified manner.

If that is the intended behavior then all is good.

**Comment by DavdGao** [comment]
Feel free to open a new issue if needed, closing this for now.

**Comment by zyzhang1130** [comment]
There is still the vision/image modality support issue has not been addressed.
