### ISSUE TITLE
Any example of IfElsePipeline(condition, agent1, agent2)?

### ISSUE THREAD

**Issue by LotusPhilip** [modelscope/agentscope#377]
Can I get an example of IfElsePipeline(condition, agent1, agent2)? I think there's no related guide in official docs.

**Comment by pan-x-c** [comment]
You can refer to the `test_if_else_pipeline` of `tests/pipeline_test.py` for simple examples.

In simple terms, the condition function is a lambda function whose input is the pipeline input Msg, and whose output is `True` or `False`. When the output is `True`, the `if_body_operators` will be executed, and when the output is `False`, the `else_body_operators` will be executed.

**Comment by LotusPhilip** [comment]
Thanks! my problem is solved.
