### ISSUE TITLE
do you use workflow? like dify

### ISSUE THREAD

**Issue by njhouse365** [modelscope/agentscope#380]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**

**To Reproduce**

1. You code
2. How to execute
3. See error

**Expected behavior**

**Error messages**
Detailed error messages.

**Environment (please complete the following information):**

- AgentScope Version: [e.g. 0.0.2 via `print(agentscope.__version__)`]
- Python Version: [e.g. 3.9]
- OS: [e.g. macos, windows]

**Additional context**

**Comment by DavdGao** [comment]
Please provide more details about the issue.

**Comment by DavdGao** [comment]
Thanks for your attention. We are working on improve workstation continuously, and any suggestions are welcomed!
