### ISSUE TITLE
[Bug]:agentscope can support linux system?

### ISSUE THREAD

**Issue by moweng** [modelscope/agentscope#399]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**

**To Reproduce**

1. You code
2. How to execute
3. See error

**Expected behavior**

**Error messages**
Detailed error messages.

**Environment (please complete the following information):**

- AgentScope Version: [e.g. 0.0.2 via `print(agentscope.__version__)`]
- Python Version: [e.g. 3.9]
- OS: [e.g. macos, windows]

**Additional context**

**Comment by DavdGao** [comment]
AgentScope supports linux by default. If you encounter any questions, plz provide more details

**Comment by DavdGao** [comment]
Feel free to open new issues if needed. closing this for now.
