### ISSUE TITLE
[Feature]: 能不能像隔壁Qwen-Agent一样添加“调度”Agent?

### ISSUE THREAD

**Issue by liyunhan** [modelscope/agentscope#405]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Is your feature request related to a problem? Please describe.**
现在的Agent调度还是固定的，确定好Agent的执行流程，能不能让Agent自己作为其它Agent的调度器？

**Describe the solution you'd like**
比如当用户随机提问的时候，一个总的Agent负责决定需要调用哪些功能模块Agent（像是套娃）

**Describe alternatives you've considered**
隔壁Qwen-Agent实现了类似的功能，但是感觉程序设计上AgentScope更具易用性，所以想你们两边能不能把思路融合一下~

**Additional context**

**Comment by DavdGao** [comment]
Thanks for your attention. 

We will take it into consideration.

**Comment by DavdGao** [comment]
Update: We will add an example for the agent router

**Comment by liyunhan** [comment]
@DavdGao 

> Update: We will add an example for the agent router

感谢大佬，以及有点疑惑，AgentScope和Qwen-agent没记错的话都是咱们通义千问团队的吧？两个项目算是独立并行？区别在哪儿？

**Comment by DavdGao** [comment]
> @DavdGao
> 
> > Update: We will add an example for the agent router
> 
> 感谢大佬，以及有点疑惑，AgentScope和Qwen-agent没记错的话都是咱们通义千问团队的吧？两个项目算是独立并行？区别在哪儿？

qwen-agent 从qwen模型本身出发，在加强以及enable一些新的能力，包括但不限于context length、使用工具；
agentscope专注于multi-agent，多个agent之间的配合，如何更加稳定、高效，以及易用。即使同一个事情，譬如调用工具，由于实际应用的要求/限制等，可能需要在不同的层面去实现。

**Comment by liyunhan** [comment]
> > @DavdGao
> > > Update: We will add an example for the agent router
> > 
> > 
> > 感谢大佬，以及有点疑惑，AgentScope和Qwen-agent没记错的话都是咱们通义千问团队的吧？两个项目算是独立并行？区别在哪儿？
> 
> qwen-agent 从qwen模型本身出发，在加强以及enable一些新的能力，包括但不限于context length、使用工具； agentscope专注于multi-agent，多个agent之间的配合，如何更加稳定、高效，以及易用。即使同一个事情，譬如调用工具，由于实际应用的要求/限制等，可能需要在不同的层面去实现。

qwen-agent倾向于能力探索，agentscope倾向于工程实践、应用落地，可以这样理解吧？

**Comment by DavdGao** [comment]
Update: The router agent is implemented as an example in PR #416

**Comment by liyunhan** [comment]
> Update: The router agent is implemented as an example in PR #416

感谢项目组
