### ISSUE TITLE
cannot import name '_is_windows' 

### ISSUE THREAD

**Issue by RyanOvO** [modelscope/agentscope#417]
报错：
`ImportError: cannot import name '_is_windows' from 'agentscope.utils.tools' (/home/apienv/lib/python3.10/site-packages/agentscope/utils/tools.py)
`

version: 0.0.5a1

**Comment by pan-x-c** [comment]
`_is_windows` is introduced in 0.0.6. Please install the latest version of Agentscope. You can install AgentScope using the latest source code by `pip install -e .`
