### ISSUE TITLE
"AttributeError: can't set attribute..."

### ISSUE THREAD

**Issue by zy1260957619** [modelscope/agentscope#423]
https://github.com/modelscope/agentscope/blob/bc2e24ba6bab26108fd350fbbc1ad51472258ea5/src/agentscope/parsers/json_object_parser.py#L95

When dealing with TagNotFoundError, an error message "AttributeError: can't set attribute..." will be reported. Because response.text is' read-only '. 'response._text 'can be used instead when' response.text 'is assigned. 

I found this issue while running 'werewolf. py' and LLMs can not provide the correct answer format. And it is just a suggestion for this code.

**Comment by DavdGao** [comment]
Thanks for your suggestion. We will fix this error in #422 , where we add `@text.setter` function to support attribute setting in model response.
