### ISSUE TITLE
where is TextToImageAgent?

### ISSUE THREAD

**Issue by MoQijie** [modelscope/agentscope#444]
Why can't I find TextToImageAgent? Is it because this agent function has been deleted? What should I do if I want to realize such a function?

**Comment by pan-x-c** [comment]
`TextToImageAgent` is changed to a service named [`dashscope_text_to_image`](https://github.com/modelscope/agentscope/blob/main/src/agentscope/service/multi_modality/dashscope_services.py).
For usage, you can refer to the DashScope section of this [example](https://github.com/modelscope/agentscope/blob/main/examples/conversation_with_customized_services/main.ipynb).

**Comment by MoQijie** [comment]
thanks a lot
