### ISSUE TITLE
[Feature]: how to i use model for together ai ?

### ISSUE THREAD

**Issue by dangyuuki123** [modelscope/agentscope#447]
hello, i don't use dashscope because i am not chinese. i want using Together AI api for model how to using this?

**Comment by DavdGao** [comment]
Welcome to AgentScope. It seems like Together AI supports post request in their [documentation](https://docs.together.ai/docs/introduction). 

Therefore, you can use the post request based model wrapper in AgentScope with the following model configuration (fill your api key)
```python
my_model_config = {
    "config_name": "my_together_ai_config",  # whatever you like
    "model_type": "post_api_chat",

    "api_url": "https://api.together.xyz/v1/chat/completions",
    "headers": {
        "Authorization": "Bearer $TOGETHER_API_KEY",
        "Content-Type": "application/json"
    },
    "json_args": {
        "model": "xxxx",
    }
}

agentscope.init(model_configs=my_model_config)
```

**Comment by Dang-Tu-lang** [comment]
@DavdGao 
thank you so much

**Comment by DavdGao** [comment]
It seems like the issue is solved. Feel free to open a new one if needed, closing this for now.
