### ISSUE TITLE
[Bug]:don't use dict(self.pydantic_class(**response.parsed))

### ISSUE THREAD

**Issue by wujiren** [modelscope/agentscope#466]
**Describe the bug**
in `MarkdownJsonDictParser`, the `parse` function use `response.parsed = dict(self.pydantic_class(**response.parsed))` to transfer pydantic model to dict, it's not good for a nested data.
you should use `response.parsed = self.pydantic_class(**response.parsed).model_dump()` instead
this is the source code
```python
        # Requirement checking by Pydantic
        if self.pydantic_class is not None:
            try:
                response.parsed = dict(self.pydantic_class(**response.parsed))
            except Exception as e:
                raise JsonParsingError(
                    message=str(e),
                    raw_response=response.text,
                ) from None
 ```
 I will show you an example

**To Reproduce**
this is an example why don't do it.
```python
from pydantic import BaseModel,Field
import json

class InsideSchema(BaseModel):
    key:str  = Field("value", description="key")

class NestedStructure(BaseModel):
    object: InsideSchema = Field(default_factory=InsideSchema, description="object")


if __name__ == "__main__":
    data = NestedStructure()
    print(data.model_dump()) # {'object': {'key': 'value'}}

    print(dict(data)) # {'object': InsideSchema(key='value')}

    try:
        json.dumps(dict(data))
    except Exception as e:
        print(e) # Object of type InsideSchema is not JSON serializable
```
the result will show that `dict(*)` won't parse complicated data, inside the 'object' is a pydantic data type `InsideSchema(key='value')`, not a dict `{'key': 'value'}`.
it will raise error when you dump the it.

**Comment by DavdGao** [comment]
@wujiren Thanks for pointing out this issue. I agree with your change. Could you please create a pull request to support nested Pydantic models?

**Comment by wujiren** [comment]
> @wujiren Thanks for pointing out this issue. I agree with your change. Could you please create a pull request to support nested Pydantic models?

sure thing, coming soon
