### ISSUE TITLE
How to stop the processing job

### ISSUE THREAD

**Issue by winger1982-lee** [modelscope/agentscope#476]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

![image](https://github.com/user-attachments/assets/ffcfb869-48ee-4313-91a6-15b072c8f0b4)

**Comment by DavdGao** [comment]
If you're running the built-in examples, in most cases, just type "exit" to quit the conversation. Optionally, you can directly kill the running application in your terminal.

**Comment by winger1982-lee** [comment]
ok, thanks
