### ISSUE TITLE
logger日志记录不支持中文解析

### ISSUE THREAD

**Issue by Weihong-Liu** [modelscope/agentscope#63]
中文只能输出Unicode字符
![image](https://github.com/modelscope/agentscope/assets/65588374/7d9cc26f-b38a-47ff-a803-91c55602f35d)

![image](https://github.com/modelscope/agentscope/assets/65588374/1fc7b433-32c0-4610-b814-7c6a0dc4fcc7)

**Comment by DavdGao** [comment]
Please provide more information about your running code and environment.

**Comment by Weihong-Liu** [comment]
[werewolf_zh.zip](https://github.com/modelscope/agentscope/files/14582989/werewolf_zh.zip)

agentscope 使用源码安装

**Comment by DavdGao** [comment]
Thanks! We will fix it as soon as possible.

**Comment by DavdGao** [comment]
The bug is fixed for now,  please pull the latest main branch.
