### ISSUE TITLE
与modelscope agent的区别

### ISSUE THREAD

**Issue by zhanpengjie** [modelscope/agentscope#65]
我正在进行agent框架选型，请问agentscope和modelscope agent的区别在哪些方面

**Comment by JianxinMa** [comment]
看起来AgentScope是一个MultiAgent分布式框架（核心是分布式，用写单机代码的思路就能自动变成分布式、并且似乎会自动识别依赖来提高并行度），而ModelScope-Agent和大部分框架一样是一个SingleAgent为主的框架、虽然有MultiAgent相关的支持但基本都是单机的（不涉及分布式）。

从AgentScope的README看，实际上我们可以在AgentScope里使用ModelScope-Agent或其他框架来实现Custom的单机Agent，比如：
```
from agentscope.agents import AgentBase

class MyAgent(AgentBase):
    def reply(self, x):
        # 使用其他单机框架来实现 do_something_with_other_agent_framework
        response = do_something_with_other_agent_framework(x)
        return response
```

（非本项目维护者，就纯路人发表下看法）

**Comment by zhanpengjie** [comment]
> 看起来AgentScope是一个MultiAgent分布式框架（核心是分布式，用写单机代码的思路就能自动变成分布式、并且似乎会自动识别依赖来提高并行度），而ModelScope-Agent和大部分框架一样是一个SingleAgent为主的框架、虽然有MultiAgent相关的支持但基本都是单机的（不涉及分布式）。
> 
> 
> 
> 从AgentScope的README看，实际上我们可以在AgentScope里使用ModelScope-Agent或其他框架来实现Custom的单机Agent，比如：
> 
> ```
> 
> from agentscope.agents import AgentBase
> 
> 
> 
> class MyAgent(AgentBase):
> 
>     def reply(self, x):
> 
>         # 使用其他单机框架来实现 do_something_with_other_agent_framework
> 
>         response = do_something_with_other_agent_framework(x)
> 
>         return response
> 
> ```
> 
> 
> 
> （非本项目维护者，就纯路人发表下看法）

谢谢，学习了

**Comment by DavdGao** [comment]
If you have any further questions or concerns, please feel free to create a new issue. Closing this for now.
