### ISSUE TITLE
关于RPC分布式部署中如何充分调用硬件设备资源（如gpu、npu等资源）[Feature]: 

### ISSUE THREAD

**Issue by appleinsky** [modelscope/agentscope#78]
我的工作需要在多型号设备中集群推理（如nvidia、昇腾的atlas、nxp的8mp等平台），但没有看到agentscope对于分布式设备的硬件调度问题，能不能和如何充分利用调度硬件设备资源，请问有相关的工做解决这方面的工作吗？

**Comment by ZiTao-Li** [comment]
感谢对agentscope的支持。目前来说，agentscope是更接近在“应用层”的框架，我们的基于actor模式的分布式机制可以提供agent执行层面的效率优化；但agentscope暂时没有涉及硬件调度/集群管理方面的组件。
 
To  @pan-x-c ：please check if I miss any information.

**Comment by pan-x-c** [comment]
目前 agentscope 主要是面向应用层，没有提供自动的硬件设备调度，如果想要充分利用硬件资源，需要使用者使用对应的推理加速工具以及硬件调度框架在对应的设备上启动模型推理服务以及 Agent。例如可以根据不同硬件的性能启动不同规模的模型推理服务。对于如何充分利用硬件设备资源提供推理服务可以参考 vLLM，tensorRT-LLM 等工作，而对于多型号设备集群的调度管理则可以使用 k8s。

**Comment by appleinsky** [comment]
Thank you reply!

**Comment by DavdGao** [comment]
Thanks for your attention, if you have any further questions or concerns, please feel free to create a new issue. 
Closing this for now.
